import React, { useEffect, useState, useCallback } from 'react';
import { PYTHON_API_URL } from '../../config/api';
import {
  buildInterviewPdfPayload,
  downloadInterviewPdf,
  downloadAtsPdf,
} from '../../utility/reportActions';
import { jsPDF } from 'jspdf';

/* ─────────────────────────── helpers ─────────────────────────── */

const sc = (n) => {
  const v = Number(n) || 0;
  if (v >= 75) return '#16a34a';
  if (v >= 50) return '#d97706';
  return '#dc2626';
};

const ScorePill = ({ value }) => (
  <span style={{
    display: 'inline-block',
    background: `${sc(value)}18`,
    color: sc(value),
    border: `1px solid ${sc(value)}40`,
    borderRadius: 9999,
    padding: '2px 10px',
    fontSize: 12,
    fontWeight: 700,
  }}>
    {Number(value) || 0}/100
  </span>
);

const SectionCard = ({ title, children, accent = '#3b82f6' }) => (
  <div style={{
    background: '#fff',
    borderRadius: 12,
    border: '1px solid #e2e8f0',
    overflow: 'hidden',
    marginBottom: 16,
  }}>
    <div style={{
      background: `${accent}0d`,
      borderBottom: `2px solid ${accent}30`,
      padding: '10px 18px',
    }}>
      <span style={{ fontWeight: 700, fontSize: 14, color: accent }}>{title}</span>
    </div>
    <div style={{ padding: '14px 18px' }}>{children}</div>
  </div>
);

const BulletList = ({ items, color = '#475569', icon = '•' }) => {
  const arr = (items || []).filter(Boolean);
  if (!arr.length) return <p style={{ color: '#94a3b8', fontSize: 13 }}>None listed.</p>;
  return (
    <ul style={{ margin: 0, padding: 0, listStyle: 'none' }}>
      {arr.map((item, i) => (
        <li key={i} style={{
          display: 'flex', gap: 8, fontSize: 13, color,
          lineHeight: 1.55, marginBottom: 6, alignItems: 'flex-start',
        }}>
          <span style={{ flexShrink: 0, marginTop: 2, fontWeight: 700 }}>{icon}</span>
          <span>{item}</span>
        </li>
      ))}
    </ul>
  );
};

const Tag = ({ label, color }) => (
  <span style={{
    background: `${color}15`,
    color,
    border: `1px solid ${color}35`,
    borderRadius: 6,
    padding: '3px 10px',
    fontSize: 12,
    fontWeight: 600,
    display: 'inline-block',
    margin: '2px',
  }}>
    {label}
  </span>
);

/* ─────────────────── resume PDF download ────────────────────── */

const downloadResumePdf = (candidateName, resume) => {
  const doc = new jsPDF();
  let y = 18;

  const safeText = (txt) => String(txt || '').replace(/[^\x00-\x7F]/g, '?');
  const section = (title, accent) => {
    if (y > 265) { doc.addPage(); y = 18; }
    doc.setFillColor(...accent);
    doc.rect(14, y - 1, 182, 8, 'F');
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(11);
    doc.setTextColor(255, 255, 255);
    doc.text(safeText(title), 16, y + 5);
    doc.setTextColor(0, 0, 0);
    y += 12;
  };
  const line = (txt, indent = 14, bold = false) => {
    if (!txt) return;
    if (y > 278) { doc.addPage(); y = 18; }
    doc.setFont('helvetica', bold ? 'bold' : 'normal');
    doc.setFontSize(10);
    const lines = doc.splitTextToSize(safeText(txt), 196 - indent);
    doc.text(lines, indent, y);
    y += lines.length * 5 + 2;
  };

  // Header
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(20);
  doc.text(safeText(candidateName || 'Candidate Resume'), 14, y);
  y += 12;
  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(100, 100, 100);
  doc.text('Generated by Interview Genius Platform', 14, y);
  doc.setTextColor(0, 0, 0);
  y += 10;

  const edu = resume?.Education || [];
  const exp = resume?.Experience || [];
  const proj = resume?.Projects || [];
  const skills = resume?.Skills || [];

  if (edu.length) {
    section('EDUCATION', [30, 64, 175]);
    edu.forEach((e) => line(`• ${e}`, 16));
    y += 4;
  }
  if (exp.length) {
    section('EXPERIENCE', [21, 128, 61]);
    exp.forEach((e) => line(`• ${e}`, 16));
    y += 4;
  }
  if (proj.length) {
    section('PROJECTS', [124, 45, 18]);
    proj.forEach((p) => line(`• ${p}`, 16));
    y += 4;
  }
  if (skills.length) {
    section('SKILLS', [88, 28, 135]);
    const chunks = [];
    for (let i = 0; i < skills.length; i += 6) chunks.push(skills.slice(i, i + 6).join('  |  '));
    chunks.forEach((c) => line(c, 16));
  }

  doc.save(`${(candidateName || 'candidate').replace(/\s+/g, '-').toLowerCase()}-resume.pdf`);
};

/* ────────────────────── tabs ─────────────────────────────────── */

const TABS = ['Overview', 'Interview Report', 'ATS Report', 'Resume'];

/* ──────────────────── main component ─────────────────────────── */

export default function InterviewReportModal({ sessionId, candidateName, applicationData, onClose }) {
  const [session, setSession] = useState(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState('');
  const [tab, setTab] = useState('Overview');

  // applicationData contains the full Application doc: resume, ats_score, ats_report, etc.
  const resume = applicationData?.resume || null;
  const atsScore = applicationData?.ats_score ?? session?.ats_score ?? 0;

  useEffect(() => {
    if (!sessionId) {
      setError('No AI interview session linked to this application.');
      setLoading(false);
      return;
    }
    const load = async () => {
      try {
        const res = await fetch(`${PYTHON_API_URL}/api/interview-session/${encodeURIComponent(sessionId)}`);
        const data = await res.json();
        if (!res.ok) throw new Error(data.error || 'Failed to load interview session');
        setSession(data);
      } catch (err) {
        setError(err.message || 'Failed to load interview report.');
      } finally {
        setLoading(false);
      }
    };
    load();
  }, [sessionId]);

  const handleDownloadFullPdf = useCallback(() => {
    if (!session) return;
    const payload = buildInterviewPdfPayload({ session });
    downloadInterviewPdf(
      `${(candidateName || 'candidate').replace(/\s+/g, '-')}-full-report.pdf`,
      payload
    );
  }, [session, candidateName]);

  const handleDownloadAtsPdf = useCallback(() => {
    const atsReport = session?.ats_report || applicationData?.ats_report || {};
    downloadAtsPdf(
      `${(candidateName || 'candidate').replace(/\s+/g, '-')}-ats-report.pdf`,
      { jobDetails: { title: session?.job_title || '' }, report: atsReport }
    );
  }, [session, applicationData, candidateName]);

  const handleDownloadResumePdf = useCallback(() => {
    downloadResumePdf(candidateName, resume);
  }, [candidateName, resume]);

  const summary = session?.summary || {};
  const responses = session?.responses || [];
  const atsReport = session?.ats_report || applicationData?.ats_report || {};
  const overallScore = summary.overall_score ?? 0;
  const decision = summary.recommended_decision || 'Pending';

  /* ── first response (may be the single-video full response) ── */
  const firstReport = responses[0]?.report || {};

  return (
    <div
      onClick={(e) => { if (e.target === e.currentTarget) onClose(); }}
      style={{
        position: 'fixed', inset: 0,
        background: 'rgba(15,23,42,0.65)',
        zIndex: 60,
        display: 'flex', alignItems: 'flex-start', justifyContent: 'center',
        padding: '20px 12px',
        overflowY: 'auto',
      }}
    >
      <div style={{
        background: '#f8fafc',
        borderRadius: 18,
        boxShadow: '0 32px 80px rgba(0,0,0,0.28)',
        width: '100%', maxWidth: 920,
        overflow: 'hidden',
        display: 'flex', flexDirection: 'column',
      }}>

        {/* ── Modal Header ── */}
        <div style={{
          background: 'linear-gradient(135deg,#1e3a8a,#2563eb)',
          padding: '22px 28px',
          display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start', gap: 12,
        }}>
          <div>
            <h2 style={{ margin: 0, color: '#fff', fontSize: 20, fontWeight: 800 }}>
              Candidate Full Report
            </h2>
            <p style={{ margin: '4px 0 0', color: '#bfdbfe', fontSize: 13 }}>
              {candidateName && <strong style={{ color: '#fff' }}>{candidateName}</strong>}
              {session?.job_title && ` — ${session.job_title}`}
              {session?.interview_type && ` (${session.interview_type})`}
            </p>
          </div>
          <div style={{ display: 'flex', gap: 8, flexWrap: 'wrap', alignItems: 'center' }}>
            {session && (
              <>
                <button
                  onClick={handleDownloadFullPdf}
                  style={{
                    background: '#fff', color: '#1e3a8a', border: 'none',
                    borderRadius: 8, padding: '7px 14px', cursor: 'pointer',
                    fontSize: 12, fontWeight: 700,
                  }}
                >
                  ⬇ Full Report PDF
                </button>
                <button
                  onClick={handleDownloadAtsPdf}
                  style={{
                    background: '#dbeafe', color: '#1e40af', border: 'none',
                    borderRadius: 8, padding: '7px 14px', cursor: 'pointer',
                    fontSize: 12, fontWeight: 700,
                  }}
                >
                  ⬇ ATS Report PDF
                </button>
              </>
            )}
            {resume && (
              <button
                onClick={handleDownloadResumePdf}
                style={{
                  background: '#dcfce7', color: '#15803d', border: 'none',
                  borderRadius: 8, padding: '7px 14px', cursor: 'pointer',
                  fontSize: 12, fontWeight: 700,
                }}
              >
                ⬇ Resume PDF
              </button>
            )}
            <button
              onClick={onClose}
              style={{
                background: 'rgba(255,255,255,0.15)', color: '#fff', border: '1px solid rgba(255,255,255,0.3)',
                borderRadius: 8, padding: '7px 14px', cursor: 'pointer',
                fontSize: 13, fontWeight: 700,
              }}
            >
              ✕
            </button>
          </div>
        </div>

        {/* ── Tab bar ── */}
        <div style={{
          display: 'flex', borderBottom: '1px solid #e2e8f0',
          background: '#fff', overflowX: 'auto',
        }}>
          {TABS.map((t) => (
            <button
              key={t}
              onClick={() => setTab(t)}
              style={{
                padding: '12px 22px', border: 'none', background: 'none',
                cursor: 'pointer', fontSize: 14, fontWeight: tab === t ? 700 : 500,
                color: tab === t ? '#2563eb' : '#64748b',
                borderBottom: tab === t ? '2px solid #2563eb' : '2px solid transparent',
                whiteSpace: 'nowrap', transition: 'all 0.15s',
              }}
            >
              {t}
              {t === 'Resume' && !resume && (
                <span style={{ marginLeft: 6, fontSize: 11, color: '#94a3b8' }}>(JSON)</span>
              )}
            </button>
          ))}
        </div>

        {/* ── Body ── */}
        <div style={{ padding: '24px 28px', overflowY: 'auto', maxHeight: '75vh' }}>

          {loading && (
            <div style={{ textAlign: 'center', padding: '64px 0', color: '#64748b' }}>
              <div style={{ fontSize: 40, marginBottom: 14 }}>⏳</div>
              Loading candidate report...
            </div>
          )}

          {error && (
            <div style={{
              background: '#fef2f2', border: '1px solid #fecaca',
              borderRadius: 10, padding: 16, color: '#dc2626', fontSize: 14,
            }}>
              {error}
            </div>
          )}

          {!loading && !error && (
            <>
              {/* ═══ OVERVIEW ═══ */}
              {tab === 'Overview' && (
                <div>
                  {/* Score cards */}
                  <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit,minmax(160px,1fr))', gap: 14, marginBottom: 22 }}>
                    {[
                      { label: 'Interview Score', value: overallScore, icon: '🎯', accent: '#2563eb' },
                      { label: 'ATS Score', value: atsScore, icon: '📄', accent: '#7c3aed' },
                      { label: 'AI Decision', raw: decision, icon: '🤖', accent: '#0891b2' },
                      { label: 'Responses', raw: `${summary.responses_completed ?? responses.length}/${summary.question_count ?? responses.length}`, icon: '💬', accent: '#059669' },
                    ].map((card) => (
                      <div key={card.label} style={{
                        background: '#fff', borderRadius: 14, padding: '18px 20px',
                        border: `1px solid ${card.accent}25`,
                        boxShadow: '0 1px 4px rgba(0,0,0,0.06)',
                      }}>
                        <div style={{ fontSize: 22, marginBottom: 6 }}>{card.icon}</div>
                        <div style={{ fontSize: 11, color: '#94a3b8', fontWeight: 700, textTransform: 'uppercase', letterSpacing: 0.8 }}>
                          {card.label}
                        </div>
                        {card.value !== undefined ? (
                          <div style={{ fontSize: 36, fontWeight: 900, color: sc(card.value), lineHeight: 1.1, marginTop: 4 }}>
                            {card.value}<span style={{ fontSize: 14, fontWeight: 400, color: '#94a3b8' }}>/100</span>
                          </div>
                        ) : (
                          <div style={{ fontSize: 16, fontWeight: 800, color: card.accent, marginTop: 4 }}>{card.raw}</div>
                        )}
                      </div>
                    ))}
                  </div>

                  {/* AI Summary */}
                  {summary.last_summary && (
                    <SectionCard title="AI Assessment Summary" accent="#2563eb">
                      <p style={{ margin: 0, fontSize: 14, color: '#374151', lineHeight: 1.7 }}>{summary.last_summary}</p>
                    </SectionCard>
                  )}

                  {/* Candidate info */}
                  <SectionCard title="Candidate Information" accent="#7c3aed">
                    <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 10, fontSize: 13 }}>
                      {[
                        ['Name', session?.candidate_name || candidateName || 'N/A'],
                        ['Email', session?.candidate_email || 'N/A'],
                        ['Role Applied', session?.job_title || 'N/A'],
                        ['Company', session?.company_name || 'N/A'],
                        ['Interview Type', session?.interview_type || 'N/A'],
                        ['Difficulty', session?.difficulty || 'N/A'],
                        ['Session Status', session?.status || 'N/A'],
                        ['Date', session?.created_at ? new Date(session.created_at).toLocaleString() : 'N/A'],
                      ].map(([k, v]) => (
                        <div key={k}>
                          <div style={{ fontSize: 11, color: '#94a3b8', fontWeight: 700, textTransform: 'uppercase', marginBottom: 2 }}>{k}</div>
                          <div style={{ color: '#1e293b', fontWeight: 600 }}>{v}</div>
                        </div>
                      ))}
                    </div>
                  </SectionCard>
                </div>
              )}

              {/* ═══ INTERVIEW REPORT ═══ */}
              {tab === 'Interview Report' && (
                <div>
                  {responses.length === 0 && (
                    <div style={{ textAlign: 'center', padding: '48px 0', color: '#94a3b8', border: '1px dashed #e2e8f0', borderRadius: 12 }}>
                      No interview responses recorded yet.
                    </div>
                  )}

                  {responses.map((resp, idx) => {
                    const r = resp.report || {};
                    const verbal = r.verbal_analysis || {};
                    const content = r.content_analysis || {};
                    const behavior = r.behavioral_analysis || {};
                    const transcript = r.transcript || {};

                    return (
                      <div key={idx} style={{ marginBottom: 24 }}>
                        <div style={{
                          background: 'linear-gradient(90deg,#1e40af,#3b82f6)',
                          borderRadius: 12, padding: '12px 18px', marginBottom: 14,
                          display: 'flex', justifyContent: 'space-between', alignItems: 'center', flexWrap: 'wrap', gap: 8,
                        }}>
                          <div>
                            <span style={{ fontSize: 11, color: '#bfdbfe', fontWeight: 700 }}>
                              {responses.length > 1 ? `QUESTION ${idx + 1}` : 'FULL INTERVIEW RESPONSE'}
                            </span>
                            <p style={{ margin: '4px 0 0', color: '#fff', fontWeight: 600, fontSize: 14 }}>
                              {resp.question || 'Interview Response'}
                            </p>
                          </div>
                          <div style={{ textAlign: 'right' }}>
                            <div style={{ fontSize: 32, fontWeight: 900, color: '#fff', lineHeight: 1 }}>
                              {r.overall_score ?? 0}
                            </div>
                            <div style={{ fontSize: 11, color: '#bfdbfe' }}>/100</div>
                          </div>
                        </div>

                        {/* Summary */}
                        {r.summary && (
                          <SectionCard title="Response Summary" accent="#2563eb">
                            <p style={{ margin: 0, fontSize: 13, color: '#374151', lineHeight: 1.65 }}>{r.summary}</p>
                            {r.recommended_decision && (
                              <div style={{ marginTop: 10 }}>
                                <span style={{ fontSize: 11, color: '#64748b', fontWeight: 600 }}>Decision: </span>
                                <strong style={{ color: '#1e293b' }}>{r.recommended_decision}</strong>
                              </div>
                            )}
                          </SectionCard>
                        )}

                        {/* Transcript */}
                        {(transcript.full_text || transcript.summary) && (
                          <SectionCard title="Transcript" accent="#0891b2">
                            {transcript.summary && (
                              <p style={{ margin: '0 0 10px', fontSize: 13, color: '#374151', fontStyle: 'italic' }}>
                                Summary: {transcript.summary}
                              </p>
                            )}
                            {transcript.full_text && (
                              <div style={{
                                background: '#f0f9ff', border: '1px solid #bae6fd',
                                borderRadius: 8, padding: '12px 14px',
                                fontSize: 13, color: '#0c4a6e',
                                whiteSpace: 'pre-wrap', lineHeight: 1.65,
                                maxHeight: 260, overflowY: 'auto',
                              }}>
                                {transcript.full_text}
                              </div>
                            )}
                          </SectionCard>
                        )}

                        {/* Verbal + Communication */}
                        {(verbal.sentiment || verbal.pace || verbal.observations) && (
                          <SectionCard title="Communication Analysis" accent="#7c3aed">
                            <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 12, marginBottom: 10 }}>
                              {verbal.sentiment && (
                                <div>
                                  <div style={{ fontSize: 11, color: '#94a3b8', fontWeight: 700, marginBottom: 3 }}>SENTIMENT</div>
                                  <strong style={{ color: '#4c1d95', fontSize: 13 }}>{verbal.sentiment}</strong>
                                </div>
                              )}
                              {verbal.pace && (
                                <div>
                                  <div style={{ fontSize: 11, color: '#94a3b8', fontWeight: 700, marginBottom: 3 }}>PACE</div>
                                  <strong style={{ color: '#4c1d95', fontSize: 13 }}>{verbal.pace}</strong>
                                </div>
                              )}
                            </div>
                            {verbal.observations && (
                              <p style={{ margin: 0, fontSize: 13, color: '#374151', lineHeight: 1.6 }}>{verbal.observations}</p>
                            )}
                            {content.content_observations && (
                              <p style={{ margin: '8px 0 0', fontSize: 13, color: '#374151', lineHeight: 1.6 }}>{content.content_observations}</p>
                            )}
                          </SectionCard>
                        )}

                        {/* Behavioral */}
                        {behavior.observations && (
                          <SectionCard title="Behavioral Analysis" accent="#0891b2">
                            <p style={{ margin: 0, fontSize: 13, color: '#374151', lineHeight: 1.6 }}>{behavior.observations}</p>
                          </SectionCard>
                        )}

                        {/* Strengths & Weaknesses side by side */}
                        <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 14, marginBottom: 14 }}>
                          <SectionCard title="✓ Strengths" accent="#16a34a">
                            <BulletList items={r.strengths} color="#166534" icon="✓" />
                          </SectionCard>
                          <SectionCard title="✗ Areas to Improve" accent="#dc2626">
                            <BulletList items={r.weaknesses} color="#991b1b" icon="✗" />
                          </SectionCard>
                        </div>

                        {/* Recommendations */}
                        {(r.recommendations || []).length > 0 && (
                          <SectionCard title="Recommendations" accent="#f59e0b">
                            <BulletList items={r.recommendations} color="#92400e" icon="→" />
                          </SectionCard>
                        )}
                      </div>
                    );
                  })}
                </div>
              )}

              {/* ═══ ATS REPORT ═══ */}
              {tab === 'ATS Report' && (
                <div>
                  {/* ATS Score + Summary */}
                  <div style={{
                    background: '#fff', borderRadius: 14, padding: '20px 24px',
                    border: '1px solid #e2e8f0', marginBottom: 18,
                    display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start',
                    flexWrap: 'wrap', gap: 16,
                  }}>
                    <div style={{ flex: 1 }}>
                      <div style={{ fontSize: 11, color: '#94a3b8', fontWeight: 700, textTransform: 'uppercase', marginBottom: 4 }}>Overall ATS Score</div>
                      <div style={{ fontSize: 48, fontWeight: 900, color: sc(atsReport.overall_score), lineHeight: 1 }}>
                        {atsReport.overall_score ?? atsScore ?? 0}
                      </div>
                      <div style={{ fontSize: 13, color: '#64748b', marginTop: 2 }}>/100</div>
                      {atsReport.summary && (
                        <p style={{ margin: '12px 0 0', fontSize: 13, color: '#374151', lineHeight: 1.6 }}>{atsReport.summary}</p>
                      )}
                    </div>
                    <button
                      onClick={handleDownloadAtsPdf}
                      style={{
                        background: '#7c3aed', color: '#fff', border: 'none',
                        borderRadius: 9, padding: '10px 20px', cursor: 'pointer',
                        fontSize: 13, fontWeight: 700, whiteSpace: 'nowrap',
                      }}
                    >
                      ⬇ Download ATS PDF
                    </button>
                  </div>

                  {/* Section Scores */}
                  {atsReport.section_scores && Object.keys(atsReport.section_scores).length > 0 && (
                    <SectionCard title="Section Scores" accent="#7c3aed">
                      <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fill,minmax(200px,1fr))', gap: 12 }}>
                        {Object.entries(atsReport.section_scores).map(([key, sec]) => (
                          <div key={key} style={{
                            background: '#faf5ff', borderRadius: 10, padding: '12px 14px',
                            border: '1px solid #e9d5ff',
                          }}>
                            <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: 4 }}>
                              <span style={{ fontSize: 12, fontWeight: 700, color: '#4c1d95' }}>
                                {key.split('_').map((w) => w[0].toUpperCase() + w.slice(1)).join(' ')}
                              </span>
                              <ScorePill value={sec.score} />
                            </div>
                            {sec.description && (
                              <p style={{ margin: 0, fontSize: 11, color: '#6d28d9', lineHeight: 1.5 }}>{sec.description}</p>
                            )}
                            <div style={{ fontSize: 10, color: '#94a3b8', marginTop: 4 }}>
                              Weight: {Math.round((sec.weight ?? 0) * 100)}%
                            </div>
                          </div>
                        ))}
                      </div>
                    </SectionCard>
                  )}

                  {/* Keyword Coverage */}
                  <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 14, marginBottom: 16 }}>
                    <SectionCard title="✓ Matched Keywords" accent="#16a34a">
                      <div style={{ display: 'flex', flexWrap: 'wrap', gap: 4 }}>
                        {(atsReport.keywords?.matched || []).length > 0
                          ? (atsReport.keywords.matched).map((kw) => <Tag key={kw} label={kw} color="#16a34a" />)
                          : <p style={{ color: '#94a3b8', fontSize: 13, margin: 0 }}>No matched keywords found.</p>}
                      </div>
                    </SectionCard>
                    <SectionCard title="✗ Missing Keywords" accent="#dc2626">
                      <div style={{ display: 'flex', flexWrap: 'wrap', gap: 4 }}>
                        {(atsReport.keywords?.missing || []).length > 0
                          ? (atsReport.keywords.missing).map((kw) => <Tag key={kw} label={kw} color="#dc2626" />)
                          : <p style={{ color: '#94a3b8', fontSize: 13, margin: 0 }}>No missing keywords found.</p>}
                      </div>
                    </SectionCard>
                  </div>

                  {/* Section Keyword Hits */}
                  {atsReport.keywords?.section_hits && (
                    <SectionCard title="Keyword Hits by Section" accent="#0891b2">
                      <div style={{ display: 'flex', flexDirection: 'column', gap: 10 }}>
                        {Object.entries(atsReport.keywords.section_hits).map(([sec, hits]) => (
                          <div key={sec}>
                            <div style={{ fontSize: 12, fontWeight: 700, color: '#0c4a6e', marginBottom: 4 }}>
                              {sec.charAt(0).toUpperCase() + sec.slice(1)}
                            </div>
                            <div style={{ display: 'flex', flexWrap: 'wrap', gap: 4 }}>
                              {(hits || []).length > 0
                                ? hits.map((kw) => <Tag key={kw} label={kw} color="#0891b2" />)
                                : <span style={{ color: '#94a3b8', fontSize: 12 }}>No hits in this section</span>}
                            </div>
                          </div>
                        ))}
                      </div>
                    </SectionCard>
                  )}

                  {/* Strengths, Weaknesses, Suggestions */}
                  <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 14, marginBottom: 14 }}>
                    <SectionCard title="Resume Strengths" accent="#16a34a">
                      <BulletList items={atsReport.strengths} color="#166534" icon="✓" />
                    </SectionCard>
                    <SectionCard title="Resume Weaknesses" accent="#dc2626">
                      <BulletList items={atsReport.weaknesses} color="#991b1b" icon="✗" />
                    </SectionCard>
                  </div>

                  {(atsReport.suggestions || []).length > 0 && (
                    <SectionCard title="Improvement Suggestions" accent="#f59e0b">
                      <BulletList items={atsReport.suggestions} color="#92400e" icon="→" />
                    </SectionCard>
                  )}

                  {(atsReport.improvement_plan || []).length > 0 && (
                    <SectionCard title="Section-by-Section Improvement Plan" accent="#6366f1">
                      <div style={{ display: 'flex', flexDirection: 'column', gap: 10 }}>
                        {atsReport.improvement_plan.map((item, i) => (
                          <div key={i} style={{
                            borderLeft: '3px solid #6366f1', paddingLeft: 12,
                          }}>
                            <div style={{ fontSize: 12, fontWeight: 700, color: '#3730a3' }}>{item.section}</div>
                            <div style={{ fontSize: 13, color: '#374151', marginTop: 2 }}>{item.action}</div>
                          </div>
                        ))}
                      </div>
                    </SectionCard>
                  )}

                  {(atsReport.formatting_issues || []).length > 0 && (
                    <SectionCard title="Formatting Issues" accent="#f59e0b">
                      <BulletList items={atsReport.formatting_issues} color="#92400e" icon="⚠" />
                    </SectionCard>
                  )}
                </div>
              )}

              {/* ═══ RESUME ═══ */}
              {tab === 'Resume' && (
                <div>
                  {!resume ? (
                    <div style={{
                      textAlign: 'center', padding: '48px 0',
                      color: '#94a3b8', border: '1px dashed #e2e8f0', borderRadius: 12,
                    }}>
                      <div style={{ fontSize: 36, marginBottom: 10 }}>📄</div>
                      <p>No resume data is attached to this application.</p>
                    </div>
                  ) : (
                    <div>
                      {/* Download button */}
                      <div style={{ display: 'flex', justifyContent: 'flex-end', marginBottom: 16 }}>
                        <button
                          onClick={handleDownloadResumePdf}
                          style={{
                            background: '#059669', color: '#fff', border: 'none',
                            borderRadius: 9, padding: '10px 20px', cursor: 'pointer',
                            fontSize: 13, fontWeight: 700,
                          }}
                        >
                          ⬇ Download Resume as PDF
                        </button>
                      </div>

                      {/* Rendered resume sections */}
                      <div style={{
                        background: '#fff', borderRadius: 14, padding: '28px 32px',
                        border: '1px solid #e2e8f0', boxShadow: '0 1px 4px rgba(0,0,0,0.06)',
                      }}>
                        {/* Header */}
                        <div style={{
                          borderBottom: '2px solid #2563eb', paddingBottom: 14, marginBottom: 20,
                        }}>
                          <h3 style={{ margin: 0, fontSize: 22, fontWeight: 800, color: '#1e293b' }}>
                            {candidateName || 'Candidate'}
                          </h3>
                          <p style={{ margin: '4px 0 0', fontSize: 13, color: '#64748b' }}>
                            Resume • Parsed by AI Platform
                          </p>
                        </div>

                        {/* Education */}
                        {resume.Education?.length > 0 && (
                          <div style={{ marginBottom: 20 }}>
                            <div style={{
                              fontSize: 11, fontWeight: 800, color: '#1d4ed8',
                              textTransform: 'uppercase', letterSpacing: 1.2, marginBottom: 8,
                              borderLeft: '3px solid #2563eb', paddingLeft: 8,
                            }}>
                              Education
                            </div>
                            {resume.Education.map((e, i) => (
                              <p key={i} style={{ margin: '0 0 5px 11px', fontSize: 13, color: '#374151', lineHeight: 1.6 }}>
                                • {e}
                              </p>
                            ))}
                          </div>
                        )}

                        {/* Experience */}
                        {resume.Experience?.length > 0 && (
                          <div style={{ marginBottom: 20 }}>
                            <div style={{
                              fontSize: 11, fontWeight: 800, color: '#15803d',
                              textTransform: 'uppercase', letterSpacing: 1.2, marginBottom: 8,
                              borderLeft: '3px solid #16a34a', paddingLeft: 8,
                            }}>
                              Experience
                            </div>
                            {resume.Experience.map((e, i) => (
                              <p key={i} style={{ margin: '0 0 5px 11px', fontSize: 13, color: '#374151', lineHeight: 1.6 }}>
                                • {e}
                              </p>
                            ))}
                          </div>
                        )}

                        {/* Projects */}
                        {resume.Projects?.length > 0 && (
                          <div style={{ marginBottom: 20 }}>
                            <div style={{
                              fontSize: 11, fontWeight: 800, color: '#b45309',
                              textTransform: 'uppercase', letterSpacing: 1.2, marginBottom: 8,
                              borderLeft: '3px solid #d97706', paddingLeft: 8,
                            }}>
                              Projects
                            </div>
                            {resume.Projects.map((p, i) => (
                              <p key={i} style={{ margin: '0 0 5px 11px', fontSize: 13, color: '#374151', lineHeight: 1.6 }}>
                                • {p}
                              </p>
                            ))}
                          </div>
                        )}

                        {/* Skills */}
                        {resume.Skills?.length > 0 && (
                          <div>
                            <div style={{
                              fontSize: 11, fontWeight: 800, color: '#6d28d9',
                              textTransform: 'uppercase', letterSpacing: 1.2, marginBottom: 8,
                              borderLeft: '3px solid #7c3aed', paddingLeft: 8,
                            }}>
                              Skills
                            </div>
                            <div style={{ display: 'flex', flexWrap: 'wrap', gap: 6, paddingLeft: 11 }}>
                              {resume.Skills.map((s, i) => (
                                <span key={i} style={{
                                  background: '#ede9fe', color: '#4c1d95',
                                  border: '1px solid #ddd6fe', borderRadius: 6,
                                  padding: '3px 10px', fontSize: 12, fontWeight: 600,
                                }}>
                                  {s}
                                </span>
                              ))}
                            </div>
                          </div>
                        )}

                        {/* Fallback if all sections empty */}
                        {!resume.Education?.length && !resume.Experience?.length &&
                         !resume.Projects?.length && !resume.Skills?.length && (
                          <p style={{ color: '#94a3b8', fontSize: 14 }}>
                            Resume data could not be parsed into sections.
                          </p>
                        )}
                      </div>
                    </div>
                  )}
                </div>
              )}
            </>
          )}
        </div>
      </div>
    </div>
  );
}
